import type { KeybindingItem } from './types';

export const DEFAULT_KEYMAPS: Omit<KeybindingItem, 'currentKey' | 'isCustomized'>[] = [
  // 1. 文本编辑与字号 (Editing & Typography)
  {
    id: 'editor:undo',
    title: '撤销',
    description: '撤销上一步编辑操作',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Z',
  },
  {
    id: 'editor:redo',
    title: '重做',
    description: '重做已撤销的编辑操作',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Y',
  },
  {
    id: 'editor:zoom-in',
    title: '增大字号',
    description: '增大编辑器字体大小',
    category: 'editing',
    scope: 'global',
    defaultKey: 'Ctrl+=',
  },
  {
    id: 'editor:zoom-out',
    title: '减小字号',
    description: '减小编辑器字体大小',
    category: 'editing',
    scope: 'global',
    defaultKey: 'Ctrl+-',
  },

  // 2. 章节与大纲导航 (Navigation)
  {
    id: 'nav:prev-chapter',
    title: '上一章',
    description: '保存当前章节并切换至上一章',
    category: 'navigation',
    scope: 'global',
    defaultKey: 'Ctrl+[',
  },
  {
    id: 'nav:next-chapter',
    title: '下一章',
    description: '保存当前章节并切换至下一章',
    category: 'navigation',
    scope: 'global',
    defaultKey: 'Ctrl+]',
  },
  {
    id: 'nav:flight-deck',
    title: '大纲手稿台',
    description: '打开分卷大纲、章节列表与灵感备忘录手稿台',
    category: 'navigation',
    scope: 'global',
    defaultKey: 'Ctrl+J',
  },
  {
    id: 'nav:scratchpad',
    title: '灵感备忘录',
    description: '打开全书设定与灵感随笔备忘录',
    category: 'navigation',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+M',
  },
  {
    id: 'nav:bookshelf',
    title: '作品书架',
    description: '切换作品或管理作品书架',
    category: 'navigation',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+B',
  },

  // 3. 查找与检索 (Search & Palette)
  {
    id: 'nav:global-search',
    title: '全书全文检索',
    description: '跨越全书分卷与章节正文进行全文搜索',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+F',
  },
  {
    id: 'search:toggle-hud',
    title: '章节查找与替换',
    description: '打开章节内查找与替换悬浮面板',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+F',
  },
  {
    id: 'search:replace-hud',
    title: '章节替换模式',
    description: '直接打开替换模式悬浮面板',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+H',
  },
  {
    id: 'nav:command-palette',
    title: '命令面板',
    description: '打开全局命令面板快速执行功能与跳转章节',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+P',
  },

  // 4. 分屏编辑 (Split View & Dual Writing)
  {
    id: 'split:toggle',
    title: '开启/关闭分屏',
    description: '开启或关闭双编辑器分屏对照',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+S',
  },
  {
    id: 'split:swap-panes',
    title: '交换分屏章节',
    description: '互换主副编辑区当前打开的章节',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+X',
  },
  {
    id: 'split:focus-toggle',
    title: '切换分屏焦点',
    description: '在主编辑区与副编辑区之间切换输入焦点',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Ctrl+\\',
  },
  {
    id: 'split:focus-primary',
    title: '聚焦主编辑区',
    description: '将输入焦点切换至左侧/上方主编辑区',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+1',
  },
  {
    id: 'split:focus-secondary',
    title: '聚焦副编辑区',
    description: '将输入焦点切换至右侧/下方副编辑区',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+2',
  },

  // 5. 排版与写作辅助 (Literary Tools)
  {
    id: 'literary:save-chapter',
    title: '保存章节',
    description: '保存当前章节手稿至本地存储',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+S',
  },
  {
    id: 'literary:format-chinese',
    title: '中文段落排版',
    description: '自动添加段首两全角空格缩进并整理空行',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+L',
  },
  {
    id: 'focus:toggle',
    title: '专注聚光灯',
    description: '开启或关闭聚光灯模式 (高亮当前段落并暗化周围)',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Alt+F',
  },
  {
    id: 'focus:toggle-scope',
    title: '切换聚光灯范围',
    description: '在段落、单句与三行微光之间切换聚焦范围',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Alt+Shift+F',
  },
  {
    id: 'literary:toggle-dialogue',
    title: '对话台词高亮',
    description: '开启或关闭引号内人物对话台词的高亮显示',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+H',
  },
  {
    id: 'novel:import-txt',
    title: '导入 TXT 小说',
    description: '从本地导入 .txt / .md 文本并自动识别分卷章节',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+I',
  },
  {
    id: 'literary:quick-export',
    title: '导出为 TXT 文本',
    description: '将全书分卷与章节内容合并导出为 .txt 文件',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+E',
  },

  // 6. 界面与系统设置 (Viewport & Settings)
  {
    id: 'view:toggle-sidebar',
    title: '切换侧边栏',
    description: '展开或折叠左侧大纲与作品导航侧栏',
    category: 'system',
    scope: 'global',
    defaultKey: 'Ctrl+B',
  },
  {
    id: 'keymap:open-cheatsheet',
    title: '快捷键速查与自定义',
    description: '打开快捷键速查面板，支持修改与自定义按键',
    category: 'system',
    scope: 'global',
    defaultKey: 'Ctrl+/',
  },
  {
    id: 'view:toggle-zen',
    title: '禅模式 (全屏写作)',
    description: '隐藏界面辅助控件，全屏纯净写作',
    category: 'system',
    scope: 'global',
    defaultKey: 'F11',
  },
  {
    id: 'view:open-settings',
    title: '打开偏好设置',
    description: '打开排版、光标、背景、主题与快捷键设置抽屉',
    category: 'system',
    scope: 'global',
    defaultKey: 'Ctrl+,',
  },
];
