import type { KeybindingItem } from './types';

export const DEFAULT_KEYMAPS: Omit<KeybindingItem, 'currentKey' | 'isCustomized'>[] = [
  // ✍️ 1. 文本编辑与行操作 (Editing & Line Operations)
  {
    id: 'editor:undo',
    title: '撤销上一步操作',
    description: '撤销最近一次的手稿输入或格式修改',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Z',
  },
  {
    id: 'editor:redo',
    title: '重做已撤销操作',
    description: '重做上一次撤销的历史手稿内容',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Y',
  },
  {
    id: 'editor:select-all',
    title: '全选手稿全文',
    description: '快速选中当前章节的全部文本内容',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+A',
  },
  {
    id: 'editor:move-line-up',
    title: '向上移动当前行/段落',
    description: '将当前行或选中的整段文字向上平移一行',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Alt+ArrowUp',
  },
  {
    id: 'editor:move-line-down',
    title: '向下移动当前行/段落',
    description: '将当前行或选中的整段文字向下平移一行',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Alt+ArrowDown',
  },
  {
    id: 'editor:insert-paragraph-below',
    title: '智能另起新自然段',
    description: '跳出当前行，在下方直接新建空行并准备写作',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Enter',
  },
  {
    id: 'editor:soft-break',
    title: '软换行 (段内换行)',
    description: '在当前段落内插入换行符而不产生新段落间距',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Shift+Enter',
  },
  {
    id: 'editor:indent',
    title: '增加两字符缩进',
    description: '在行首插入或增加中文标准缩进',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Tab',
  },
  {
    id: 'editor:outdent',
    title: '减少缩进',
    description: '向左删除行首缩进空格',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Shift+Tab',
  },
  {
    id: 'editor:delete-word-backward',
    title: '向前整词删除',
    description: '快速删除光标前方的一个完整词汇或标点块',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Backspace',
  },
  {
    id: 'editor:delete-word-forward',
    title: '向后整词删除',
    description: '快速删除光标后方的一个完整词汇或标点块',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Delete',
  },
  {
    id: 'editor:select-line',
    title: '快速选中当前整行',
    description: '选中光标所在行的所有文本内容',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+L',
  },
  {
    id: 'editor:select-next-occurrence',
    title: '选中当前词 / 多选下一个',
    description: '高亮当前词，多次按下可在手稿中追加多光标选区',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+D',
  },
  {
    id: 'editor:delete-line',
    title: '删除当前整行/整段',
    description: '一键删除当前光标所在行，下方行自动吸合',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+Shift+K',
  },
  {
    id: 'editor:toggle-h1',
    title: '设为章回标题 (一级标题)',
    description: '在行首添加/切换 # 一级大标题',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+1',
  },
  {
    id: 'editor:toggle-h2',
    title: '设为分卷小节 (二级标题)',
    description: '在行首添加/切换 ## 二级小标题',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+2',
  },
  {
    id: 'editor:toggle-h0',
    title: '清除标题恢复正文',
    description: '清除行首 # 标记，恢复为普通段落',
    category: 'editing',
    scope: 'editor',
    defaultKey: 'Ctrl+0',
  },

  // 🚀 2. 光标疾速巡航 (Cursor Navigation)
  {
    id: 'nav:line-start',
    title: '跳转至当前行首',
    description: '光标瞬间移动到当前行的最开头',
    category: 'navigation',
    scope: 'editor',
    defaultKey: 'Home',
  },
  {
    id: 'nav:line-end',
    title: '跳转至当前行尾',
    description: '光标瞬间移动到当前行的最末尾',
    category: 'navigation',
    scope: 'editor',
    defaultKey: 'End',
  },
  {
    id: 'nav:doc-start',
    title: '瞬移至篇首 (手稿最开篇)',
    description: '快速滚动并聚焦到当前手稿的第一行开头',
    category: 'navigation',
    scope: 'editor',
    defaultKey: 'Ctrl+Home',
  },
  {
    id: 'nav:doc-end',
    title: '瞬移至篇末 (手稿最尾端)',
    description: '快速滚动并聚焦到当前手稿的最后一个字符',
    category: 'navigation',
    scope: 'editor',
    defaultKey: 'Ctrl+End',
  },
  {
    id: 'nav:jump-prev-word',
    title: '光标向前按词跳跃',
    description: '光标向前跳过一个完整词语',
    category: 'navigation',
    scope: 'editor',
    defaultKey: 'Ctrl+ArrowLeft',
  },
  {
    id: 'nav:jump-next-word',
    title: '光标向后按词跳跃',
    description: '光标向后跳过一个完整词语',
    category: 'navigation',
    scope: 'editor',
    defaultKey: 'Ctrl+ArrowRight',
  },

  // 🔍 3. 查找、替换与检索 (Search & Navigation)
  {
    id: 'search:toggle-hud',
    title: '先锋悬浮查找与替换',
    description: '唤起极速悬浮查找与正则替换面板',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+F',
  },
  {
    id: 'search:replace-hud',
    title: '先锋悬浮批量替换',
    description: '直接以批量替换模式唤起悬浮面板',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+H',
  },
  {
    id: 'search:find-next',
    title: '查找下一个匹配项',
    description: '高亮并跳转至下一个搜索匹配结果',
    category: 'search',
    scope: 'editor',
    defaultKey: 'F3',
  },
  {
    id: 'search:find-prev',
    title: '查找上一个匹配项',
    description: '高亮并跳转至上一个搜索匹配结果',
    category: 'search',
    scope: 'editor',
    defaultKey: 'Shift+F3',
  },
  {
    id: 'nav:command-palette',
    title: '全局指令面板 (Command Palette)',
    description: '唤起快速搜索执行全部创作指令与插件功能的控制台',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+P',
  },
  {
    id: 'nav:flight-deck',
    title: '章节快速飞行检索器',
    description: '无缝唤起手稿章节全局快速检索与瞬时跳转浮层',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+J',
  },
  {
    id: 'nav:bookshelf',
    title: '藏书阁分卷与目录大纲管理',
    description: '展开查看全书分卷、章节目录树及字数概览',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+B',
  },
  {
    id: 'nav:prev-chapter',
    title: '跳转至上一章节',
    description: '直接保存当前内容并快速载入前一章节手稿',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+[',
  },
  {
    id: 'nav:next-chapter',
    title: '跳转至下一章节',
    description: '直接保存当前内容并快速载入后一章节手稿',
    category: 'search',
    scope: 'global',
    defaultKey: 'Ctrl+]',
  },

  // 🪟 4. 对等分屏与双写对照 (Split View & Dual Writing)
  {
    id: 'split:toggle',
    title: '开启 / 关闭对照分屏',
    description: '展开或关闭对等双编辑器进行章节对比与协同写作',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+S',
  },
  {
    id: 'split:focus-toggle',
    title: '主副窗格焦点切换',
    description: '在左栏主编辑器与右栏副编辑器之间无缝跳转光标聚焦',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Ctrl+\\',
  },
  {
    id: 'split:focus-primary',
    title: '快速聚焦左/上主窗格',
    description: '瞬间将输入焦点定位至主创作窗格',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+1',
  },
  {
    id: 'split:focus-secondary',
    title: '快速聚焦右/下副窗格',
    description: '瞬间将输入焦点定位至副参考/双写窗格',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+2',
  },
  {
    id: 'split:swap-panes',
    title: '左右/上下窗格章节对调',
    description: '快速将左右窗格正在编辑的章节内容进行互换',
    category: 'split_view',
    scope: 'global',
    defaultKey: 'Alt+X',
  },

  // 📖 5. 排版、文学工具与导出 (Literary Tools)
  {
    id: 'focus:toggle',
    title: '切换段落专注聚光灯',
    description: '照亮当前正在写作的段落，平滑暗化周围文字',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Alt+F',
  },
  {
    id: 'focus:toggle-scope',
    title: '切换聚光范围模式',
    description: '在逻辑段落、单句推敲与三行微光渐变间快速切换',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Alt+Shift+F',
  },
  {
    id: 'literary:save-chapter',
    title: '手稿即时安全保存',
    description: '将当前手稿内容即时保存并持久化落盘至本地文件系统',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+S',
  },
  {
    id: 'literary:format-chinese',
    title: '中文标点与空格智能排版',
    description: '一键清洗半角标点、修复破折号省略号并规范段落排版',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+L',
  },
  {
    id: 'literary:toggle-spotlight',
    title: '段落聚光灯聚焦模式',
    description: '高亮当前正在撰写的自然段，其余段落优雅暗化',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+F',
  },
  {
    id: 'literary:toggle-dialogue',
    title: '角色台词与对话智能高亮',
    description: '为手稿中所有人物台词渲染专属微光，增强剧情对话张力',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+H',
  },
  {
    id: 'literary:quick-export',
    title: '一键极速导出当前手稿',
    description: '快速将当前手稿导出为 TXT、EPUB 或 Markdown 文件',
    category: 'literary',
    scope: 'global',
    defaultKey: 'Ctrl+Shift+E',
  },

  // 🎨 6. 视口、心流与快捷键管理 (Viewport & Keymap Center)
  {
    id: 'keymap:open-cheatsheet',
    title: '快捷键全景速查与管理中心',
    description: '唤起全景交互式快捷键速查面板，支持改键与一键触发',
    category: 'system',
    scope: 'global',
    defaultKey: 'Ctrl+/',
  },
  {
    id: 'view:toggle-zen',
    title: '禅模式沉浸全屏',
    description: '隐藏所有多余界面元素，进入绝对纯粹的写作心流',
    category: 'system',
    scope: 'global',
    defaultKey: 'F11',
  },
  {
    id: 'view:open-settings',
    title: '偏好设置中心',
    description: '打开主题配色、灵感光标、背景氛围与排版参数配置抽屉',
    category: 'system',
    scope: 'global',
    defaultKey: 'Ctrl+,',
  },
];
